name: lint-conventional-commits

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: taiki-e/cache-cargo-install-action@v2
      #   with:
      #     tool: convco

      # - name: Check conventional commits formatting
      #   id: cc-lint
      #   continue-on-error: true
      #   shell: bash
      #   run: |
      #     convco check '${{ github.event.pull_request.base.sha }}'..'${{ github.event.pull_request.head.sha }}'

      - name: Install commitsar
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4
        with:
          repo: aevea/commitsar
          tag: v0.20.2
          cache: enable

      - name: Check commits
        id: cc-lint
        continue-on-error: true
        run: |
          commitsar -v -s=false

      - name: Explain conventional commits in comment
        uses: marocchino/sticky-pull-request-comment@5ec44f8ee5ecf07ea2e7410866738fb7890eb756
        with:
          header: tip-conventional-commits
          delete: ${{ steps.cc-lint.outcome == 'success' }}
          recreate: ${{ steps.cc-lint.outcome != 'success' }}
          message: |
            <h3>

            :warning: It looks like your commit is not formatted in line with [Conventional Commits][cc]

            </h3>

            The [wasmCloud][wasmcloud] project uses Conventional Commits to enable automation and ensure consistent commit messages across the project.

            If you're feeling adventurous, amend/interactively rebase your commits to match the conventional commit standard.

            For example, if you added a feature to the wasmCloud host:

            ```console
            git amend -m "feat(host): your awesome new feature title here"
            ```

            If you don't feel comfortable doing this, don't worry -- a project maintainer will help correct this for you, before merging.

            [cc]: https://www.conventionalcommits.org/en/v1.0.0
            [wasmcloud]: https://github.com/wasmCloud

      - name: Propagate lint failure
        if: ${{ steps.cc-lint.outcome != 'success' }}
        run: |
          exit -1
