name: wash

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/wash.yml
      - Cargo.lock
      - Cargo.toml
      - crates/wash-cli/**
      - crates/wash-lib/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  unit_tests:
    name: Unit Tests
    strategy:
      fail-fast: false # Ensure we can run the full suite even if one OS fails
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ matrix.os }}-shared-cache"
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: bisect
        working-directory: ./crates/wash-cli
        shell: bash
        run: |
          git bisect start;
          git bisect bad HEAD;
          git bisect good 0a08cd88;
          git bisect run \
            cargo nextest run \
              --profile ci \
              -p wash-lib \
              -p wash-cli \
              --all-features \
              -E 'binary(wash)' \
              -E 'package(wash-lib)' \
              integration_help_subcommand_check
